### ISSUE TITLE
同时引入spring-cloud-alibaba-seata和seata-spring-boot-starter依赖，出现启动阶段无法读取ConfigProperties.class（SpringUtils.getBean抛出空指针异常）

### ISSUE THREAD

**Issue by blackbk** [seata/seata#2076]
### Ⅰ. Issue Description

  经排查，必须在@SpringApplication注解内手动exclude掉spring-cloud-alibaba-seata内的com.alibaba.cloud.seata.GlobalTransactionAutoConfiguration自动装配类，使用seata-spring-boot-starter内的io.seata.spring.boot.autoconfigure.SeataAutoConfiguration对GlobalTransactionScanner进行装配。否则项目运行时会优先使用GlobalTransactionAutoConfiguration进行装配，导致在启动加载阶段报错（”io.seata.common.exception.NotSupportYetException: not support register type: null“），报错位置为io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider#get(String dataId)，该方法在使用seata的spring工具类SpringUtils.getBean(propertyClass)从ApplicationContext中获取ConfigProperties.class的Bean时（第106行），因无法从容器中到符合要求的Bean而抛出NullPoinException异常.

依赖列表：
```
  <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-seata</artifactId>
            <version>2.1.1.RELEASE</version>
 </dependency>

<dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-all</artifactId>
            <version>1.0.0</version>
 </dependency>

 <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.0.0</version>
 </dependency>
```

### Ⅱ. 配置文件

```
seata:
  enabled: true
  registry:
    type: nacos
    nacos:
      namespace: b28a1bd9-31eb-416b-8864-xxxxxxxxxxxx
      server-addr: 127.0.0.1:8848
  config:
    type: nacos
    nacos:
      namespace: b28a1bd9-31eb-416b-8864-xxxxxxxxxxxx
      server-addr: 127.0.0.1:8848
  tx-service-group: my_test
```

### Ⅲ. 环境
Jdk 8
spring-boot: 2.1.10.RELEASE
spring-cloud: 2.1.3.RELEASE
spring-cloud-alibaba: 2.1.1.RELEAS
