### ISSUE TITLE
将配置参数改为application.yml后的问题

### ISSUE THREAD

**Issue by HongKing** [seata/seata#2114]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
尝试将registry.conf和file.conf配置到application.yml中，目前发现一下两个问题，
1. undo相关配置不生效（估计seata.client.rm.lock相关属性也有类似问题）
2. service.disable-global-transaction不生效

### Ⅱ. Describe what happened
application.yml的配置
```
seata:
  enabled: true
  tx-service-group: my_test_tx_group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  client:
    rm-report-success-enable: true
    rm-table-meta-check-enable: false # 自动刷新缓存中的表结构（默认false）
    rm-report-retry-count: 5 # 一阶段结果上报TC重试次数（默认5）
    rm-async-commit-buffer-limit: 1000 # 异步提交缓存队列长度（默认10000）
    rm:
      lock:
        lock-retry-internal: 10 # 校验或占用全局锁重试间隔（默认10ms）
        lock-retry-times:    30 # 校验或占用全局锁重试次数（默认30）
        lock-retry-policy-branch-rollback-on-conflict: true # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
    tm-commit-retry-count:   3 # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
    tm-rollback-retry-count: 3 # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
    undo:
      undo-data-validation: true # 二阶段回滚镜像校验（默认true开启）
      undo-log-serialization: jackson # undo序列化方式（默认jackson）
      undo-log-table: undo_log  # 自定义undo表名（默认undo_log）
    log:
      exceptionRate: 100 # 日志异常输出概率（默认100）
    support:
      spring-datasource-autoproxy: true # 数据源自动代理开关（默认false关闭）
  service:
    vgroup-mapping: default # TC 集群（必须与seata-server保持一致）
    enable-degrade: false # 降级开关
    disable-global-transaction: false # 禁用全局事务（默认false）
  transport:
    enable-client-batch-send-request: true # 客户端事务消息请求是否批量合并发送（默认true）
  registry:
    type: eureka
    eureka:
      serviceUrl: ${eureka.host}
```
#### 问题1分析：undo相关配置不生效
`UndoProperties`中的属性有undo前缀
```
@ConfigurationProperties(prefix = UNDO_PREFIX)
public class UndoProperties {
    private boolean undoDataValidation = true;
    private String undoLogSerialization = "jackson";
    private String undoLogTable = TRANSACTION_UNDO_LOG_DEFAULT_TABLE;
    ...
}
```
而跟踪到`SpringBootConfigurationProvider`的103行时，却获取的是`seata.client.undo.logTable`
```
    private Object get(String dataId) throws IllegalAccessException {
// 此时拿到的dataId = seata.client.undo.logTable
        String propertySuffix = getPropertySuffix(dataId);
        Class propertyClass = getPropertyClass(getPropertyPrefix(dataId));
        if (null != propertyClass) {
            Object propertyObject = SpringUtils.getBean(propertyClass);
            Optional<Field> fieldOptional = Stream.of(propertyObject.getClass().getDeclaredFields()).filter(
                f -> f.getName().equalsIgnoreCase(propertySuffix)).findAny();
// 因为属性中只有undoLogTable，没有logTable，因此此时读取不到yml中的配置，返回null，采用系统默认
            if (fieldOptional.isPresent()) {
                Field field = fieldOptional.get();
                field.setAccessible(true);
                return field.get(propertyObject);
            }
        }
        return null;
    }
```
#### 问题2分析： service.disable-global-transaction不生效
跟踪代码，确实取到yml中的配置了，但是后面还是输出错误
```
[2019-12-31 10:55:43.746] [configOperate_2_2] [WARN ] io.seata.config.FileConfiguration [266] - Could not found property service.disableGlobalTransaction, try to use default value instead.
```
然后增加一个`file.conf`，添加以下内容，在启动时则没有该错误
```
service {
  disableGlobalTransaction = false
}
```

### Ⅵ. Environment:

- JDK version : 1.8
- OS : win10、centos7
- seata: 1.0.0
- seata-spring-boot-starter : 1.0.0

**Comment by zjinlei** [comment]
1. 1.0.0 changed the name of the parameters 
refer http://seata.io/zh-cn/docs/user/configurations.html
2.only config.type=file, currently using your solution

**Comment by zjinlei** [comment]
Sorry, I reconfirmed the first question.

**Comment by HongKing** [comment]
`ClientProperties`中的`seata.client.reportSuccessEnable`也有类似情况，我估计这些配置参数最好都查一下。

**Comment by AlphaHinex** [comment]
When using `nacos` as registry and config's type, could not even use `yml` to replace `registry.conf`. Reproducible example is [here](https://github.com/AlphaHinex/seata-at-demo/tree/seata-at).

Add below configs in `bootstrap.yml` and remove `registry.conf` in each service module,

```
seata:
  registry:
    type: nacos
    nacos:
      server-addr: nacos
  config:
    type: nacos
    nacos:
      server-addr: nacos
```

start the service, then will get these logs:

```
 INFO 4347 --- [           main] io.seata.config.FileConfiguration        : The file name of the operation is registry.conf
......
ERROR 4347 --- [imeoutChecker_2] i.s.c.r.netty.NettyClientChannelManager  : no available service 'null' found, please make sure registry config correct
ERROR 4347 --- [imeoutChecker_2] i.s.c.r.netty.NettyClientChannelManager  : no available service 'null' found, please make sure registry config correct
......
```

**Comment by Isaac-Zhang** [comment]
```yaml
seat:
  service:
    vgroup-mapping: my_test_tx_group
    #在spring-configuration-metadata.json中找到属性如下，但是不生效
    disable-global-transaction: false 
    #在配置类中使用如下，依然不生效
    disableGlobalTransaction: false
```
