### ISSUE TITLE
no available service 'null' found, please make sure registry config correct

### ISSUE THREAD

**Issue by CrazyShaQuiShi** [seata/seata#2374]
nacos上服务显示是已注册上去的
![image](https://user-images.githubusercontent.com/12770161/76162653-aa57b300-617a-11ea-921f-77261d6b79d6.png)
移除spring-cloud-alibaba-seata依赖，customer也可以调用到provider服务
可是引入spring-cloud-alibaba-seata 配置完成后出现如下错误提示。
![image](https://user-images.githubusercontent.com/12770161/76162668-d2471680-617a-11ea-8ed3-a11353520b38.png)

**Comment by CrazyShaQuiShi** [comment]
什么原因导致的呢？

**Comment by slievrly** [comment]
> 什么原因导致的呢？

go to seata. io  can find the answer to the question.

**Comment by GongchuangSu** [comment]
> > 什么原因导致的呢？
> 
> go to seata. io can find the answer to the question.

真是太难找了，能否直接给个答案，这个问题貌似很普遍

**Comment by GongchuangSu** [comment]
可能的原因：需指定事务分组，且名称需保持一致

- `file.conf`：service.vgroupMapping.**egova-service-media-fescar-service-group** = "default"

- `application.yml`：

  ```
  spring:
    cloud:
      alibaba:
        seata:
          tx-service-group: egova-service-media-fescar-service-group
  ```
