### ISSUE TITLE
eureka&db模式下file.conf的db模式不生效问题

### ISSUE THREAD

**Issue by jipeigong** [seata/seata#2532]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

在对seata docker-compose 高可用部署时（阿里云VPC内网两台seata server）（注册中心使用eureka，模式使用db模式），db模式无法正常生效，具体体现在执行时提示错误找不到xid（链路跨越了一台seata server），并且修改了file.conf中的db配置为错误时也不提示，启动日志中也没有关于连接数据库的信息，我猜测file.conf配置没有生效，尝试过很多方式包括将name = "file.conf"  为 name="file:/root/seata-config/file.conf",以及将file.conf映射到容器内部/seata-server/resources默认文件夹中依然无效，具体配置如下（registry.conf和file.conf都放在./config文件夹中，并且已进入容器内部看到配置文件已正确存在目标位置）：

```
    seata-server:
      image: seataio/seata-server:latest
      container_name: "seata-server"
      hostname: "seata"
      restart: always
      networks:
        - aiNetwork
      volumes:
        - ./config:/root/seata-config
      environment:
        - SEATA_IP:${SERVER_IP1}
        - STORE_MODE=file
        - SERVER_NODE=1
        - SEATA_CONFIG_NAME=file:/root/seata-config/registry
        - TZ=Asia/Shanghai
```

registry.conf ：

```
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "eureka"

  eureka {
    serviceUrl = "http://192.168.1.46:8761/eureka,http://192.168.1.48:8761/eureka"
    application = "default"
    weight = "1"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "file"

  file {
    name = "file.conf"  #（此处修改了很多方式，包括使用file:/root/seata-config/file.conf 依然无效）
  }
}
```

file.conf：
```
## transaction log store, only used in seata-server
store {
  ## store mode: file、db
  mode = "db"

  ## file store property
  file {
    ## store location dir
    dir = "sessionStore"
    # branch session size , if exceeded first try compress lockkey, still exceeded throws exceptions
    maxBranchSessionSize = 16384
    # globe session size , if exceeded throws exceptions
    maxGlobalSessionSize = 512
    # file buffer size , if exceeded allocate new buffer
    fileWriteBufferCacheSize = 16384
    # when recover batch read size
    sessionReloadReadSize = 100
    # async, sync
    flushDiskMode = async
  }

  ## database store property
  db {
    ## the implement of javax.sql.DataSource, such as 
     DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "dbcp"
    ## mysql/oracle/h2/oceanbase etc.
    dbType = "mysql"
    driverClassName = "com.mysql.jdbc.Driver"
    url = "jdbc:mysql://*/seata"
    user = "****"
    password = "****"
    minConn = 10
    maxConn = 200
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    queryLimit = 500
  }
}
```

### Ⅱ. Describe what happened

db模式无法正常生效，具体体现在执行时提示错误找不到xid（链路跨越了一台seata server），并且修改了file.conf中的db配置为错误时也不提示，启动日志中也没有关于连接数据库的信息

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8
- OS : centos7.6
- Others:
