### ISSUE TITLE
no available service 'xxxx' found, please make sure registry config correct

### ISSUE THREAD

**Issue by cielswift** [seata/seata#2834]
seata version 1.2
nacos version 1.3

```
  type = "nacos"
		
  nacos {
    application = "appId"
    serverAddr = "127.0.0.1:13100,127.0.0.1:13101,127.0.0.1:13102"
    namespace = "a998603d-3546-4ddc-9099-2ed82a6f3a68"
    cluster = "seataServer"
  }
```

![image](https://user-images.githubusercontent.com/42295829/85914920-9218ba80-b875-11ea-9bcb-711b2b8f74cb.png)

```
seata:
  enabled: true 
  application-id: appId 
  service:
    vgroupMapping: seataServer 
  registry:
    nacos:
      serverAddr: 127.0.0.1:13100,127.0.0.1:13101,127.0.0.1:13102
      namespace: a998603d-3546-4ddc-9099-2ed82a6f3a68
    type: nacos
  config:
    file:
      name: file.conf
    type: file
```

2020-06-27 12:50:04.626 ERROR [producer10,,,] 25360 --- [           main] i.s.c.r.netty.NettyClientChannelManager  : no available service 'seataServer' found, please make sure registry config correct
2020-06-27 12:50:06.010 ERROR [producer10,,,] 25360 --- [imeoutChecker_1] i.s.c.r.netty.NettyClientChannelManager  : no available service 'seataServer' found, please make sure registry config correct
2020-06-27 12:50:06.010 ERROR [producer10,,,] 25360 --- [imeoutChecker_2] i.s.c.r.netty.NettyClientChannelManager  : no available service 'seataServer' found, please make sure registry config correct

**Comment by a364176773** [comment]
http://seata.io/zh-cn/docs/user/transaction-group.html

**Comment by cielswift** [comment]
```
seata:
  enabled: true 
  application-id: appId
  tx-service-group: my_test_tx_group
  service:
    vgroupMapping: producer10  
  registry:
    nacos:
      serverAddr: 127.0.0.1:13100,127.0.0.1:13101,127.0.0.1:13102
      namespace: a998603d-3546-4ddc-9099-2ed82a6f3a68
      cluster: seataServer
    type: nacos
  config:
    file:
      name: file.conf
    type: file
```
