### ISSUE TITLE
求大佬，搞了一周无果，奔溃了：no available service 'null' found, please make sure registry config correct

### ISSUE THREAD

**Issue by arraycto** [seata/seata#2849]
seata1.2.0
nacos1.2.1
问题`springboot项目报错
`
```
2020-07-01 22:19:37.866  INFO 14268 --- [           main] io.seata.config.FileConfiguration        : The configuration file used is seata.conf
2020-07-01 22:19:38.207 ERROR 14268 --- [           main] i.s.c.r.netty.NettyClientChannelManager  : no available service 'null' found, please make sure registry config correct
2020-07-01 22:19:38.239  INFO 14268 --- [           main] .s.s.a.d.SeataAutoDataSourceProxyCreator : Auto proxy of [shardingDataSource]`
```

已经设置：
service.vgroupMapping.my_test_tx_group=default
service.default.grouplist=xx.xx.xx.xx:8091

同时config.txt
```
transport.type=TCP
transport.server=NIO
transport.heartbeat=true
transport.enableClientBatchSendRequest=false
transport.threadFactory.bossThreadPrefix=NettyBoss
transport.threadFactory.workerThreadPrefix=NettyServerNIOWorker
transport.threadFactory.serverExecutorThreadPrefix=NettyServerBizHandler
transport.threadFactory.shareBossWorker=false
transport.threadFactory.clientSelectorThreadPrefix=NettyClientSelector
transport.threadFactory.clientSelectorThreadSize=1
transport.threadFactory.clientWorkerThreadPrefix=NettyClientWorkerThread
transport.threadFactory.bossThreadSize=1
transport.threadFactory.workerThreadSize=default
transport.shutdown.wait=3
service.vgroupMapping.my_test_tx_group=default
service.default.grouplist=xx.xx.xx.xx:8091
service.enableDegrade=false
service.disableGlobalTransaction=false
client.rm.asyncCommitBufferLimit=10000
client.rm.lock.retryInterval=10
client.rm.lock.retryTimes=30
client.rm.lock.retryPolicyBranchRollbackOnConflict=true
client.rm.reportRetryCount=5
client.rm.tableMetaCheckEnable=false
client.rm.sqlParserType=druid
client.rm.reportSuccessEnable=false
client.rm.sagaBranchRegisterEnable=false
client.tm.commitRetryCount=5
client.tm.rollbackRetryCount=5
store.mode=file
store.file.dir=file_store/data
store.file.maxBranchSessionSize=16384
store.file.maxGlobalSessionSize=512
store.file.fileWriteBufferCacheSize=16384
store.file.flushDiskMode=async
store.file.sessionReloadReadSize=100
store.db.datasource=druid
store.db.dbType=mysql
store.db.driverClassName=com.mysql.jdbc.Driver
store.db.url=jdbc:mysql://xx.xx.xx.xx.:3306/seata?useUnicode=true
store.db.user=root
store.db.password=root
store.db.minConn=5
store.db.maxConn=30
store.db.globalTable=global_table
store.db.branchTable=branch_table
store.db.queryLimit=100
store.db.lockTable=lock_table
store.db.maxWait=5000
server.recovery.committingRetryPeriod=1000
server.recovery.asynCommittingRetryPeriod=1000
server.recovery.rollbackingRetryPeriod=1000
server.recovery.timeoutRetryPeriod=1000
server.maxCommitRetryTimeout=-1
server.maxRollbackRetryTimeout=-1
server.rollbackRetryTimeoutUnlockEnable=false
client.undo.dataValidation=true
client.undo.logSerialization=jackson
server.undo.logSaveDays=7
server.undo.logDeletePeriod=86400000
client.undo.logTable=undo_log
client.log.exceptionRate=100
transport.serialization=seata
transport.compressor=none
metrics.enabled=false
metrics.registryType=compact
metrics.exporterList=prometheus
metrics.exporterPrometheusPort=9898
```

**Comment by YunSD** [comment]
好巧，我也是，在更新了springboot2.3.1之后发现的此问题

**Comment by YunSD** [comment]
我又仔细检查了一遍，与spring boot版本无关，在alibaba 2.2.0.RELEASE中，seata无法正常注册服务

**Comment by arraycto** [comment]
dubbo2.7.5  springboot2.2.6 表示上面的错误。阿里大佬指点一下思路呗。奔溃了

**Comment by cmonkey** [comment]
弄个demo ，大家好调试，不然很难定位错误

**Comment by arraycto** [comment]
demo例子就是参考这个：https://github.com/lidong1665/seata-spring-boot-dubbo-nacos-shardingsphere-examples.git

这个例子跑不起来，报如题的错误，求大佬指点一下。

**Comment by arraycto** [comment]
demo例子就是参考这个：https://github.com/lidong1665/seata-spring-boot-dubbo-nacos-shardingsphere-examples.git

这个例子跑不起来，报如题的错误，求大佬指点一下。@cmonkey

**Comment by cmonkey** [comment]
> demo例子就是参考这个：https://github.com/lidong1665/seata-spring-boot-dubbo-nacos-shardingsphere-examples.git
> 
> 这个例子跑不起来，报如题的错误，求大佬指点一下。@cmonkey

2020-07-02 16:57:44.373 ERROR 2800246 --- [imeoutChecker_2] i.s.c.r.netty.NettyClientChannelManager  : no available service 'null' found, please make sure registry config correct

类似这种，你需要检查是否有类似下面的配置
![image](https://user-images.githubusercontent.com/664050/86338998-a0a40f00-bc85-11ea-8350-69ea5763b345.png)

**Comment by arraycto** [comment]
大佬，已经确认。有和这个类似的，依旧报如题的错误。如下
请问这个什么原因？搞了一周，天天睡不着啊， 
![大佬](https://user-images.githubusercontent.com/37463247/86352816-fcc45e80-bc98-11ea-856b-f6abcf493805.png)
![大佬1](https://user-images.githubusercontent.com/37463247/86352818-fd5cf500-bc98-11ea-9103-b2f6e50753ca.png)

**Comment by arraycto** [comment]
@cmonkey @作者@阿里风清扬

**Comment by arraycto** [comment]
有跑成功的大佬们，指点一下思路。跪谢

**Comment by YunSD** [comment]
建议检查seata与RM的版本是否匹配

**Comment by arraycto** [comment]
都是1.2.0的额

**Comment by YunSD** [comment]
你要不要尝试下seata 1.1.0 与RM1.1，我目前出现了seata1.2注册不上RM1.2，但是可以注册至1.1，但是我同你的配置不同，你并没有使用alibaba could

**Comment by YunSD** [comment]
![image](https://user-images.githubusercontent.com/18546121/86360002-55e5bf80-bca4-11ea-9a91-46d04217f98e.png)
这是我在seata1.2中发现的问题，还在寻找解决方法

**Comment by arraycto** [comment]
是个思路额。准备1.1搞一下，我用的dubbo2.7.x进行融合的，不想出现cloud相关，还未融合springcloud alibaba；rm的版本，您怎么看到的大佬。

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.6.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <artifactId>seata-spring-boot-dubbo-nacos-shardingsphere-examples</artifactId>
    <packaging>pom</packaging>
    <name>seata-spring-boot-dubbo-nacos-shardingsphere-examples</name>
    <groupId>io.seata</groupId>
    <version>1.2.0</version>
    <description>Demo project for Spring Boot Dubbo</description>

    <modules>
        <module>samples-common-service</module>
        <module>samples-account-service</module>
        <module>samples-order-service</module>
        <module>samples-storage-service</module>
        <module>samples-business-service</module>
    </modules>

    <properties>
        <springboot.verison>2.2.6.RELEASE</springboot.verison>
        <java.version>1.8</java.version>
        <lombok.version>1.18.12</lombok.version>
        <dubbo.version>2.7.7</dubbo.version>
        <nacos-client.verison>1.2.1</nacos-client.verison>
        <seata.version>1.2.0</seata.version>
        <sharding-sphere.version>4.1.0</sharding-sphere.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>${springboot.verison}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <version>${springboot.verison}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${springboot.verison}</version>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.1</version>
        </dependency>


        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
            <version>${dubbo.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>spring</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>${dubbo.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.apache.dubbo/dubbo-config-spring -->
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-configcenter-nacos</artifactId>
            <version>${dubbo.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <version>${dubbo.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-metadata-report-nacos</artifactId>
            <version>${dubbo.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.seata/seata-all -->

        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>${seata.version}</version>
        </dependency>


        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>${nacos-client.verison}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <version>${springboot.verison}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5</version>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.47</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
            <version>${sharding-sphere.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>${sharding-sphere.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-transaction-base-seata-at</artifactId>
            <version>${sharding-sphere.version}</version>
        </dependency>

        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>3.3.1</version>
        </dependency>
    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

```

**Comment by arraycto** [comment]
有没有seata1.2成功过的大佬，点进来的大神们，留个言，也让我能看见希望。

**Comment by cmonkey** [comment]
![image](https://user-images.githubusercontent.com/664050/86422002-6a5ea200-bd0e-11ea-9e84-b32973de260b.png)
![image](https://user-images.githubusercontent.com/664050/86422013-70548300-bd0e-11ea-8b3a-415f3b7e996e.png)
可能需要自己检查一下seata-server 这边的配置, 在example 项目里面也可以去NacosRegistryServiceImpl 中打个断点看看

**Comment by arraycto** [comment]
@YunSD  您好，您的，file.conf 和regitstry.conf麻烦发过来，参考一下呗。刚测试了seata1.1版本依旧无果，还是错误 i.s.c.r.netty.NettyClientChannelManager  : no available service 'null' found, please make sure registry config correct

**Comment by arraycto** [comment]
我用的是release的zip包，是不是必须下载源码编译才可以，看你们下载是源代码编译调试。

**Comment by arraycto** [comment]
centos7.6 jdk1.8  seata1.1/1.2  nacos1.2.1 springboot2.2.6

**Comment by cmonkey** [comment]
不好意思，我是用master 测试的，将example 对seata 版本修改为了1.3.0-SNAPSHOT, 这是没有问题的， 你看看自1.2.0 之后发生了一些什么变更，应该是在那之后fix 了

**Comment by arraycto** [comment]
nacos的服务中seata-server，是否证明，seata安装配置成功了？方便看一下您的file.conf 和regitstry.conf

**Comment by arraycto** [comment]
@cmonkey

**Comment by arraycto** [comment]
@slievrly

**Comment by arraycto** [comment]
file.conf
```

## seata-service
service {
  #交易服务组映射 的组名称必须要与客户端一致 my_test_tx_group  seata-server必须要与registrt.conf 一致
  #transaction service group mapping
  #TODO 修改 hxlh_tx_group为自己设置的事务组名称，seata-server不是事务组的名称，这里可以随便起名
  vgroupMapping.my_test_tx_group = "seata-server"
  #only support when registry.type=file, please don't set multiple addresses
  #TODO 这里设置ip, 一般不用改 因为我是安装在内网了
  default.grouplist = "192.168.186.128:8091"
  #disable seata
  disableGlobalTransaction = false
}


## transaction log store, only used in seata-server
store {
  ## store mode: file、db
  ##TODO 修改为数据库类型
  mode = "db"

  ## file store property
  file {
    ## store location dir
    dir = "sessionStore"
    # branch session size , if exceeded first try compress lockkey, still exceeded throws exceptions
    maxBranchSessionSize = 16384
    # globe session size , if exceeded throws exceptions
    maxGlobalSessionSize = 512
    # file buffer size , if exceeded allocate new buffer
    fileWriteBufferCacheSize = 16384
    # when recover batch read size
    sessionReloadReadSize = 100
    # async, sync
    flushDiskMode = async
  }

  ## database store property
  #TODO 下面这一堆就安装自己MySQL去改就行了，使用的库便是我们上面创建的seata库
  db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "druid"
    ## mysql/oracle/postgresql/h2/oceanbase etc.
    dbType = "mysql"
    driverClassName = "com.mysql.jdbc.Driver"
    url = "jdbc:mysql://127.0.0.1:3306/seata"
    user = "root"
    password = "root"
    minConn = 5
    maxConn = 30
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    queryLimit = 100
    maxWait = 5000
  }
}
```

regitstry.conf

```

registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  #TODO 配置为nacos
  type = "nacos"

#TODO 设置你自己的nacos即可
  nacos {
    application = "seata-server"
    serverAddr = "192.168.186.128:8848"
    namespace = "a70f5328-e56c-47f8-984f-da7f134d9151"
    cluster = "default"
    username = "nacos"
    password = "nacos"
  }
  eureka {
    serviceUrl = "http://localhost:8761/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = 0
    password = ""
    cluster = "default"
    timeout = 0
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  consul {
    cluster = "default"
    serverAddr = "127.0.0.1:8500"
  }
  etcd3 {
    cluster = "default"
    serverAddr = "http://localhost:2379"
  }
  sofa {
    serverAddr = "127.0.0.1:9603"
    application = "default"
    region = "DEFAULT_ZONE"
    datacenter = "DefaultDataCenter"
    cluster = "default"
    group = "SEATA_GROUP"
    addressWaitTime = "3000"
  }
  file {
    name = "file.conf"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "nacos"

  nacos {
    serverAddr = "192.168.186.128:8848"
    namespace = "a70f5328-e56c-47f8-984f-da7f134d9151"
    group = "SEATA_GROUP"
    username = "nacos"
    password = "nacos"
  }
  consul {
    serverAddr = "127.0.0.1:8500"
  }
  apollo {
    appId = "seata-server"
    apolloMeta = "http://192.168.1.204:8801"
    namespace = "application"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  etcd3 {
    serverAddr = "http://localhost:2379"
  }
  file {
    name = "file.conf"
  }
}

```

**Comment by arraycto** [comment]
我的注册中心文件打包，大佬可以直接导入nacos中查看详情，跪求。搞了9天，奔溃了。
附件如下：
[nacos_config_export_20200703111224.zip](https://github.com/seata/seata/files/4867611/nacos_config_export_20200703111224.zip)

**Comment by huguirong** [comment]
用的 `seata:1.2.0` + 配置中心 `nacos:1.3.0` + 注册中心 `eureka` ，`spring cloud` 版本是 `Greenwich.RELEASE`，没有出现问题

**Comment by arraycto** [comment]
@huguirong Centos7 ？

**Comment by huguirong** [comment]
> @huguirong Centos7 ？

和服务器没有关系。我想确认一下，你 `seata` 的 `server端` 与 `client端` （`spring boot`） 的 `registry.type` 与 `config.type` 都是 `nacos` 对吗？ 如果是，那只用去`Nacos`上看看服务列表的同一个命名空间下它们有没有注册上去就好了（不过我看你前面的描述貌似 `client端`两个`type`都是 `file` ?）

**Comment by arraycto** [comment]
yml已经改了，是nacos的哈

```
server:
  port: 8102
spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds0?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 1111
    sharding:
      tables:
        t_account:
          actual-data-nodes: ds0.t_account$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: t_account$->{id % 2}
    props:
      sql.show: true

#====================================Dubbo config===============================================
dubbo:
  application:
    id: dubbo-account-example
    name: dubbo-account-example
    qosEnable: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20883
  registry:
    id: dubbo-account-example-registry
    address: nacos://192.168.186.128:8848?namespace=a70f5328-e56c-47f8-984f-da7f134d9151
  config-center:
    address: nacos://192.168.186.128:8848?namespace=a70f5328-e56c-47f8-984f-da7f134d9151
  metadata-report:
    address: nacos://192.168.186.128:8848?namespace=a70f5328-e56c-47f8-984f-da7f134d9151
#====================================mybatis-plus config===============================================
mybatis-plus:
  mapperLocations: classpath*:/mapper/*.xml
  typeAliasesPackage: io.seata.samples.integration.*.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

#====================================Seata Config===============================================

seata:
  enabled: true
  application-id: account-seata-example
  tx-service-group: my_test_tx_group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  registry:
    file:
      name: file.conf
    type: nacos
    nacos:
      server-addr: 192.168.186.128:8848
      namespace: a70f5328-e56c-47f8-984f-da7f134d9151
      cluster: default
  config:
    file:
      name: file.conf
    type: nacos
    nacos:
      namespace: a70f5328-e56c-47f8-984f-da7f134d9151
      server-addr: 192.168.186.128:8848
      group: DEFAULT_GROUP
  enable-auto-data-source-proxy: true
  use-jdk-proxy: true
```
