### ISSUE TITLE
1.4.2 将整个config.txt文件导入nacos作为seata的配置无效(nacos作为配置、注册中心)

### ISSUE THREAD

**Issue by zxiaozhou** [seata/seata#3872]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
1.4.2 nacos配置文件形式的配置文件，1.4.2seata获取不到

### Ⅱ. Describe what happened

seata registry配置如下
```
onfig:
  # file、nacos 、apollo、zk、consul、etcd3
  type: nacos

  nacos:
    serverAddr: kubernetes.docker.internal:8848
    namespace: mac_skillfull
    group: DEFAULT_GROUP
    username: skillfull
    password: skillfull
    dataId: seataServer.properties
```
所有config.txt内容放入nacos中dataId为seataServer.properties配置文件中，，启动后获取不到配置的值，seata的namespaces，group都与配置文件一直

```
Just paste your stack trace here!
```

#### 一、失败方案
1. 将所有config.txt内容放入properties文件中并导入nacos，同时设置文件中service.vgroupMapping.my_test_tx_group1=default
2. 配置seata配置中心的dataid为上一步文件id
3. 启动seata以及需要使用分布是事务的服务
4. 此时发现客户端获提示:can not get cluster name in registry config 'service.vgroupMapping.my_test_tx_group
#### 二、成功方案
1. 将失败方案中相同配置的config.txt直接通过官方提供脚本把所有内容导入nacos（此时是单条的值了），重复上面3，4步骤(其他都没变，就导入配置方式不一样，一个是文件，，一个是单条数据)，
2. 此时一切正常
### Ⅴ. Anything else we need to know?

seata 1.4.2不是支持直接使用文件作为配置的吗？？为啥会失败，，或者说我哪配置不对，，还麻烦提供一个案例或者支出配置错误的地方

### Ⅵ. Environment:

- JDK version : 11
- OS :mac 
- Others: seata服务端、客户端都是1.4.2
