### ISSUE TITLE
The latest docker image cannot be registered to nacos

### ISSUE THREAD

**Issue by xuzhijvn** [seata/seata#4609]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

seata version: `docker.io/seataio/seata-server:latest `
docker version: `19.03.12`
k8s version: 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

The latest docker image cannot be registered to nacos:

```
apiVersion: v1
kind: Service
metadata:
  name: seata-server
  namespace: yshop-cloud
  labels:
    k8s-app: seata-server
spec:
  type: NodePort
  ports:
    - port: 8091
      nodePort: 30091
      protocol: TCP
      name: http
  selector:
    k8s-app: seata-server

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata-server
  namespace: yshop-cloud
  labels:
    k8s-app: seata-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: seata-server
  template:
    metadata:
      labels:
        k8s-app: seata-server
    spec:
      containers:
        - name: seata-server
          image: docker.io/seataio/seata-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SEATA_CONFIG_NAME
              value: file:/root/seata-config/registry
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          volumeMounts:
            - name: seata-config
              mountPath: /root/seata-config
      volumes:
        - name: seata-config
          configMap:
            name: seata-server-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-server-config
data:
  registry.conf: |
    registry {
        type = "nacos"
        nacos {
          application = "seata-server"
          serverAddr = "nacos-0.nacos-headless.yshop-cloud.svc.cluster.local:8848,nacos-1.nacos-headless.yshop-cloud.svc.cluster.local:8848,nacos-2.nacos-headless.yshop-cloud.svc.cluster.local:8848"
          group = "YSHOP_CLOUD"
          namespace = "e9234393-1ce4-4195-9937-5328ef05872b"
        }
    }
    config {
      type = "nacos"
      nacos {
        serverAddr = "nacos-0.nacos-headless.yshop-cloud.svc.cluster.local:8848,nacos-1.nacos-headless.yshop-cloud.svc.cluster.local:8848,nacos-2.nacos-headless.yshop-cloud.svc.cluster.local:8848"
        group = "YSHOP_CLOUD"
        namespace = "e9234393-1ce4-4195-9937-5328ef05872b"
      }
    }
```
Just change the version to 1.4.2 and it works fine：

```
apiVersion: v1
kind: Service
metadata:
  name: seata-server
  namespace: yshop-cloud
  labels:
    k8s-app: seata-server
spec:
  type: NodePort
  ports:
    - port: 8091
      nodePort: 30091
      protocol: TCP
      name: http
  selector:
    k8s-app: seata-server

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata-server
  namespace: yshop-cloud
  labels:
    k8s-app: seata-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: seata-server
  template:
    metadata:
      labels:
        k8s-app: seata-server
    spec:
      containers:
        - name: seata-server
          image: docker.io/seataio/seata-server:1.4.2
          imagePullPolicy: IfNotPresent
          env:
            - name: SEATA_CONFIG_NAME
              value: file:/root/seata-config/registry
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          volumeMounts:
            - name: seata-config
              mountPath: /root/seata-config
      volumes:
        - name: seata-config
          configMap:
            name: seata-server-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-server-config
data:
  registry.conf: |
    registry {
        type = "nacos"
        nacos {
          application = "seata-server"
          serverAddr = "nacos-0.nacos-headless.yshop-cloud.svc.cluster.local:8848,nacos-1.nacos-headless.yshop-cloud.svc.cluster.local:8848,nacos-2.nacos-headless.yshop-cloud.svc.cluster.local:8848"
          group = "YSHOP_CLOUD"
          namespace = "e9234393-1ce4-4195-9937-5328ef05872b"
        }
    }
    config {
      type = "nacos"
      nacos {
        serverAddr = "nacos-0.nacos-headless.yshop-cloud.svc.cluster.local:8848,nacos-1.nacos-headless.yshop-cloud.svc.cluster.local:8848,nacos-2.nacos-headless.yshop-cloud.svc.cluster.local:8848"
        group = "YSHOP_CLOUD"
        namespace = "e9234393-1ce4-4195-9937-5328ef05872b"
      }
    }

```
