### ISSUE TITLE
docker中seata配置了宿主机ip，但是启动后显示是容器内ip？

### ISSUE THREAD

**Issue by liyanzu0926** [seata/seata#4633]
docker-compos文件如下：

````yml
version: "3.3"

networks:
  my_network:

services:
  nacos:
    image: nacos/nacos-server:v2.1.0
    ports:
      - "8848:8848"
    environment:
      - "JVM_XMS=256m"
      - "JVM_XMX=256m"
      - "MODE=standalone"
    networks:
      - my_network

  seata-server:
    image: seataio/seata-server:1.4.2
    container_name: "seata-server"
    ports:
      - "8091:8091"
    networks:
      - my_network
    environment:
      - SEATA_PORT=8091
      - SEATA_IP=192.168.150.3 # 宿主机ip
    volumes:
      - /home/lyz/seata/seata-server:/seata-server
````

启动后查看nacos中seata-server服务发现ip为容器内ip

[![X93Qat.png](https://s1.ax1x.com/2022/05/23/X93Qat.png)](https://imgtu.com/i/X93Qat)

我的register.conf配置如下
````yml
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "nacos"

  nacos {
    application = "seata-server"
    serverAddr = "192.168.150.3:8848"
    group = "SEATA_GROUP"
    namespace = "34e7a459-f486-4300-a20a-80cc763b58ac"
    cluster = "default"
    username = "nacos"
    password = "nacos"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "nacos"

  nacos {
    serverAddr = "192.168.150.3:8848"
    namespace = "34e7a459-f486-4300-a20a-80cc763b58ac"
    group = "SEATA_GROUP"
    username = "nacos"
    password = "nacos"
    dataId = "seataServer.properties"
  }
  file {
    name = "file.conf"
  }
}
````

file.conf配置如下：
````yml
store {
  ## store mode: file、db、redis
  mode = "db"
  ## rsa decryption public key
  publicKey = ""
 
  db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp)/HikariDataSource(hikari) etc.
    datasource = "druid"
    ## mysql/oracle/postgresql/h2/oceanbase etc.
    dbType = "mysql"
    driverClassName = "com.mysql.cj.jdbc.Driver"
    ## if using mysql to store the data, recommend add rewriteBatchedStatements=true in jdbc connection param
    url = "jdbc:mysql://192.168.150.3:3306/seata?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true"
    user = "root"
    password = "123456"
    minConn = 5
    maxConn = 100
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    queryLimit = 100
    maxWait = 5000
  }
}
````

帮忙看下是什么原因，谢谢
