### ISSUE TITLE
seata-server-1.5.1.tar.gz: deployment -m/-h invalid

### ISSUE THREAD

**Issue by Seekingscholars** [seata/seata#4692]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
macOS 

Multiple network cards
en12 (169.254.49.207) - 无效网卡
en7 (192.168.20.52) / en6 - 正在使用网卡

seata-server-1.5.1.tar.gz

application.yml 如下
```
server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/seata

console:
  user:
    username: seata-server
    password: seata-server

seata:
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: nacos
    nacos:
      server-addr: 192.168.20.52:8848
      #namespace: "" # ""为nacos保留public空间控件，用户勿配置namespace = "public"
      group: SEATA_SERVER_GROUP
      data-id: seataServer.properties
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: nacos
    nacos:
      server-addr: 192.168.20.52:8848
      #namespace: "" # ""为nacos保留public空间控件，用户勿配置namespace = "public"
      application: seata-server
      group: SEATA_SERVER_GROUP
      cluster: SEATA_SERVER_CLUSTER
  store:
    # support: file 、 db 、 redis
    # Server端存储模式（store.mode）现有file、db、redis三种（后续将引入raft,mongodb），file模式无需改动，直接启动即可，下面专门讲下db和redis启动步骤。
    #注： file模式为单机模式，全局事务会话信息内存中读写并持久化本地文件root.data，性能较高;
    # db模式为高可用模式，全局事务会话信息通过db共享，相应性能差些;
    # redis模式Seata-Server 1.3及以上版本支持,性能较高,存在事务信息丢失风险,请提前配置合适当前场景的redis持久化配置.
    mode: db
    db:
      datasource: druid
      db-type: mysql
      #driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
      #url: jdbc:mysql://127.0.0.1:3306/seata-server-1.5?useUnicode=true&useInformationSchema=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      url: jdbc:mysql://192.168.20.52:3306/seata-server-1.5?rewriteBatchedStatements=true
      user: username
      password: password
      min-conn: 5
      max-conn: 100
      global-table: global_table
      branch-table: branch_table
      lock-table: lock_table
      distributed-lock-table: distributed_lock
      query-limit: 100
      max-wait: 5000
```

./bin/seata-server.sh -h 192.168.20.52 -p 8091 -m db -n 1

### Ⅱ. Describe what happened

secure Ant [pattern='/api/v1/auth/login'] with []
18:36:35.581  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@21e360a, org.springframework.security.web.context.SecurityContextPersistenceFilter@22ef9844, org.springframework.security.web.header.HeaderWriterFilter@169e6180, org.springframework.security.web.authentication.logout.LogoutFilter@1a18644, io.seata.console.filter.JwtAuthenticationTokenFilter@5ba3f27a, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@3b6ddd1d, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@611889f4, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@58d75e99, org.springframework.security.web.session.SessionManagementFilter@7205765b, org.springframework.security.web.access.ExceptionTranslationFilter@20ccf40b, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@2c35e847]
18:36:35.622  INFO --- [                     main] o.a.coyote.http11.Http11NioProtocol      : Starting ProtocolHandler ["http-nio-7091"]
18:36:35.650  INFO --- [                     main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 7091 (http) with context path ''
18:36:35.661  INFO --- [                     main] io.seata.server.ServerApplication        : Started ServerApplication in 3.602 seconds (JVM running for 4.416)
18:36:36.133  INFO --- [                     main] i.s.core.rpc.netty.NettyServerBootstrap  : Server started, service listen port: 8091
18:36:36.147  INFO --- [                     main] com.alibaba.nacos.client.naming          : initializer namespace from System Property :null
18:36:36.169  INFO --- [                     main] com.alibaba.nacos.client.naming          : [BEAT] adding beat: BeatInfo{port=8091, ip='169.254.49.207', weight=1.0, serviceName='SEATA_SERVER_GROUP@@seata-server', cluster='SEATA_SERVER_CLUSTER', metadata={}, scheduled=false, period=5000, stopped=false} to beat map.
18:36:36.170  INFO --- [                     main] com.alibaba.nacos.client.naming          : [REGISTER-SERVICE] public registering service SEATA_SERVER_GROUP@@seata-server with instance: Instance{instanceId='null', ip='169.254.49.207', port=8091, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='SEATA_SERVER_CLUSTER', serviceName='null', metadata={}}
18:36:36.176  INFO --- [                     main] io.seata.server.ServerRunner             : seata server started in 513 millSeconds

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
./bin/seata-server.sh -h 192.168.20.52 -p 8091 -m db -n 1

host : 192.168.20.52
storeMode : db

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. download : https://github.com/seata/seata/releases/download/v1.5.1/seata-server-1.5.1.tar.gz
2. config : application.yml
3. start : ./bin/seata-server.sh -h 192.168.20.52 -p 8091 -m db -n 1

### Ⅵ. Environment:

- JDK version : OpenJDK 1.8
- Seata version:  1.5.0
- OS : macOS
- Others:
