### ISSUE TITLE
Data too long for column 'lock_value'

### ISSUE THREAD

**Issue by wanghongzhou** [seata/seata#4695]
### Ⅰ. Issue Description
An error occurs when starting Seata in nacOS 2.1 and Seata 1.5.1 cluster deployment.  Try to modify the LOCK_value column definition in the distributed_LOCK table.  When the length is greater than or equal to 25, the console exception disappears immediately. When the length is smaller than 25, exceptions are frequently thrown. 

### Ⅱ. Describe what happened

docker-componse script:
```
services:
  seata-cluster-node1:
    image: ${SEATA_IMAGE}
    container_name: seata-cluster-node1
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SEATA_IP=${SEATA_CLUSTER_NODE1_HOST}
      - SEATA_PORT=${SEATA_CLUSTER_NODE1_PORT_8091}
    volumes:
      - ${SEATA_CLUSTER_HOME}/node1/logs:/root/logs
      - ${SEATA_CLUSTER_HOME}/node1/application.yml:/seata-server/resources/application.yml
    networks:
      - mysql
      - nacos
      - seata-cluster
    ports:
      - ${SEATA_CLUSTER_NODE1_PORT_7091}:7091
      - ${SEATA_CLUSTER_NODE1_PORT_8091}:${SEATA_CLUSTER_NODE1_PORT_8091}
  seata-cluster-node2:
    image: ${SEATA_IMAGE}
    container_name: seata-cluster-node2
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SEATA_IP=${SEATA_CLUSTER_NODE2_HOST}
      - SEATA_PORT=${SEATA_CLUSTER_NODE2_PORT_8091}
    volumes:
      - ${SEATA_CLUSTER_HOME}/node2/logs:/root/logs
      - ${SEATA_CLUSTER_HOME}/node2/application.yml:/seata-server/resources/application.yml
    networks:
      - mysql
      - nacos
      - seata-cluster
    ports:
      - ${SEATA_CLUSTER_NODE2_PORT_7091}:7091
      - ${SEATA_CLUSTER_NODE2_PORT_8091}:${SEATA_CLUSTER_NODE2_PORT_8091}
  seata-cluster-node3:
    image: ${SEATA_IMAGE}
    container_name: seata-cluster-node3
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SEATA_IP=${SEATA_CLUSTER_NODE3_HOST}
      - SEATA_PORT=${SEATA_CLUSTER_NODE3_PORT_8091}
    volumes:
      - ${SEATA_CLUSTER_HOME}/node3/logs:/root/logs
      - ${SEATA_CLUSTER_HOME}/node3/application.yml:/seata-server/resources/application.yml
    networks:
      - mysql
      - nacos
      - seata-cluster
    ports:
      - ${SEATA_CLUSTER_NODE3_PORT_7091}:7091
      - ${SEATA_CLUSTER_NODE3_PORT_8091}:${SEATA_CLUSTER_NODE3_PORT_8091}
```

```
seata-cluster-node2    | 05:32:10.626 ERROR --- [      AsyncCommitting_1_1] i.s.s.s.d.l.DataBaseDistributedLocker    : execute acquire lock failure, key is: AsyncCommitting
seata-cluster-node2    | ==>
seata-cluster-node2    | com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'lock_value' at row 1
seata-cluster-node2    |        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
seata-cluster-node2    |        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
seata-cluster-node2    |        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
seata-cluster-node2    |        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
seata-cluster-node2    |        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
seata-cluster-node2    |        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
seata-cluster-node2    |        at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255)
seata-cluster-node2    |        at io.seata.server.storage.db.lock.DataBaseDistributedLocker.updateDistributedLock(DataBaseDistributedLocker.java:246)
seata-cluster-node2    |        at io.seata.server.storage.db.lock.DataBaseDistributedLocker.acquireLock(DataBaseDistributedLocker.java:129)
seata-cluster-node2    |        at io.seata.server.session.SessionHolder.acquireDistributedLock(SessionHolder.java:375)
seata-cluster-node2    |        at io.seata.server.session.SessionHolder.distributedLockAndExecute(SessionHolder.java:397)
seata-cluster-node2    |        at io.seata.server.coordinator.DefaultCoordinator.lambda$init$7(DefaultCoordinator.java:491)
seata-cluster-node2    |        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
seata-cluster-node2    |        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
seata-cluster-node2    |        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
seata-cluster-node2    |        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
seata-cluster-node2    |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
seata-cluster-node2    |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
seata-cluster-node2    |        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
seata-cluster-node2    |        at java.lang.Thread.run(Thread.java:748)
seata-cluster-node2    | <==
```

### Ⅵ. Environment:

- Seata version:  1.5.1
- OS : Linux VM-20-2-centos 4.18.0-348.7.1.el8_5.x86_64
