### ISSUE TITLE
[分享] seata:1.5.2结合nacos:2.1.0，seata-spring-boot-starter:1.5.2，相关的配置

### ISSUE THREAD

**Issue by pptech-dev** [seata/seata#4776]
### nacos
图1
![图1](https://user-images.githubusercontent.com/84951843/178926188-0f044537-6a7d-4445-b36c-3deb8d64dab8.png)
图2
![图2](https://user-images.githubusercontent.com/84951843/178926297-d4cad6b6-ea39-4a46-a105-8b0f518b723b.png)
图3
![图3](https://user-images.githubusercontent.com/84951843/178926416-c439211d-4358-4cfd-a859-1938337cef62.png)

### 项目配置application.yml
```
# 完整配置: https://github.com/seata/seata/blob/develop/script/client/spring/application.yml
seata:
  application-id: ${spring.application.name}
  enable-auto-data-source-proxy: false
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.0.143:8848
      group: SEATA_GROUP
      namespace: 02cf7241-260b-4d3b-ae1a-459bfc540007
      username: nacos
      password: nacos
      application: seata-server # 注意这个，跟图3的服务名要一致的
  config:
    type: nacos
    nacos:
      server-addr: 192.168.0.143:8848
      group: SEATA_GROUP
      namespace: 02cf7241-260b-4d3b-ae1a-459bfc540007
      username: nacos
      password: nacos
  tx-service-group: main_tx_group
```

感觉文档对于这些参数的解释不是很清楚（或者是我没好好的理解到文档？），经过调试代码，断点各种请求才最终成功！

FYI
nacos的主机防火墙，要同时开放8848，7848，9848，9849的端口，才能保证正常访问。
