### ISSUE TITLE
seata saga mode transaction

### ISSUE THREAD

**Issue by zfhlm** [seata/seata#4785]
How to retry rollback when an exception occurs during rollback.

Should rollback be 100% successful through business processing?

**Comment by zfhlm** [comment]
# must add configuration properties

seata:
  enabled: true
  enable-auto-data-source-proxy: false
  saga:
    enabled: true
    state-machine:
      application-id: ${seata.application-id}
      resources: 'classpath:statelang/*.json'
      rm-report-success-enable: true
      saga-branch-register-enable: true
      saga-compensate-persist-mode-update: true
      saga-retry-persist-mode-update: true

**Comment by zfhlm** [comment]
# must add application.yml configuration

```
seata:
  enabled: true
  enable-auto-data-source-proxy: false
  saga:
    enabled: true
    state-machine:
      application-id: ${seata.application-id}
      resources: 'classpath:statelang/*.json'
      rm-report-success-enable: true
      saga-branch-register-enable: true
      saga-compensate-persist-mode-update: true
      saga-retry-persist-mode-update: true
```
