### ISSUE TITLE
sharding-jdbc4.1.1 分库分表报重复字段问题

### ISSUE THREAD

**Issue by davidhhuan** [seata/seata#4873]
# 相应版本
seata: 1.5.2
sharding-jdbc: 4.1.1

# 分库分表策略
```
      # 注意，我这里同时采取了分库，以及分表
       order_return:
          actualDataNodes: ds${0..3}.order_return_${0..7}
          databaseStrategy: # 分库策略
            inline:
              shardingColumn: buyer_id
              algorithmExpression: ds${buyer_id % 4}
          tableStrategy: # 分表策略
            inline:
              shardingColumn: buyer_id #分表列名称
              algorithmExpression: order_return_${(buyer_id / 4 as long) % 8} #分表算法
          keyGenerator:
            column: id
            type: SNOWFLAKE
            props:
              worker.id: ${shardingSphereWorkerId}
```

# 报错
![image](https://user-images.githubusercontent.com/449399/185429188-bcdc20f7-54b3-4de1-8bf9-b7853359e09f.png)

# 分析如下
![image](https://user-images.githubusercontent.com/449399/185428366-df9568e5-8e74-4cef-b294-2f2df83bd9ff.png)
如上所示，在查找表结构的时候，执行的那条SQL把所有库和所有表都扫出来了，关于问题在这里
![image](https://user-images.githubusercontent.com/449399/185428719-f0cdba0e-2881-4b90-ac39-e385f350ae12.png)
在读取所有库所有表的结构的时候（因为这些物理表，对应的逻辑表order_return，结构都是相同的），就报了以上错误了！
