### ISSUE TITLE
高可用部署面临的问题

### ISSUE THREAD

**Issue by liruhui** [seata/seata#4905]
## 1: 问题说明
```properties
1:  docker部署注册中心nacos  部署seata  部署mysql 
2：seata的数据持久化到mysql中 并且注册到nacos注册中心  
3：微服务从nacos注册中心 通过集群名称获取seata时 只能注册到默认8091端口  其他端口注册不上
```
### 2.1. 启动2个seata 
```properties
 ## 启动第一个seata 
docker run -d --name seata -p8091:8091 -p7091:7091 -e SEATA_IP=192.168.198.128  -e SEATA_PORT=8091 -e SERVER_NODE=1 -v /opt/application.yml:/seata-server/resources/application.yml seataio/seata-server:1.5.2

## 启动第二个seata
docker run -d --name seata2 -p8899:8091 -p7788:7091 -e SEATA_IP=192.168.198.128 -e SEATA_PORT=8899 -e SERVER_NODE=2 -v /opt/application.yml:/seata-server/resources/application.yml seataio/seata-server:1.5.2
```
### 2.2. 注册中心信息正常
![fff](https://user-images.githubusercontent.com/24687986/188273365-9435d8e0-3739-468d-854f-22c5c711cbde.png)

### 2.3. 客户端配置
```yaml
seata:
  enable-auto-data-source-proxy: false
  service:
    vgroup-mapping:
      huige: abcdefg #集群名称
  tx-service-group: huige
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.198.128:8848
      cluster: abcdefg #集群名称
      namespace: public
      group: SEATA_GROUP
```
### 2.4. 问题说明
```properties
  有2个seata，端口分别是8091和8899 但是客户端能注册到8091(下图一)，但是无法连接8899(下图二)。
```
![uuuu](https://user-images.githubusercontent.com/24687986/188273530-c14c161e-ca13-4192-b79c-1951eaf6e0ec.jpg)

![eee](https://user-images.githubusercontent.com/24687986/188272744-6ea25eb9-5100-4545-9279-6642e046294a.png)
