### ISSUE TITLE
console输入账号密码登录没反应

### ISSUE THREAD

**Issue by S540J521** [seata/seata#5407]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
k8s容器化部署seata-server 1.6.1，在web输入ip:7091访问seata，输入application.yml（console.user.username/password）中设置的账号和密码登录没反应也没提示任何错误信息
账号密码都输入seata也是这样

**Comment by luojiasheng** [comment]
容器7091，映射端口也是一样吗？我之前也出现过这种情况后来删除重新部署就好了

**Comment by S540J521** [comment]
> 容器7091，映射端口也是一样吗？我之前也出现过这种情况后来删除重新部署就好了
麻烦看看哪里需要改动
**application.yml端口设置如下**
![image](https://user-images.githubusercontent.com/124575445/222642770-ff43ba93-837c-4858-9188-5904943644c3.png)

**k8s部署脚本内容如下**
```
apiVersion: v1
kind: Service
metadata:
  name: seata-server
  namespace: default
  labels:
    k8s-app: seata-server
spec:
  type: ClusterIP
  ports:
    - port: 8091
      protocol: TCP
      name: service
    - port: 7091
      protocol: TCP
      name: console
  selector:
    k8s-app: seata-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata-server
  namespace: default
  labels:
    k8s-app: seata-server
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: seata-server
  template:
    metadata:
      labels:
        k8s-app: seata-server
    spec:
      containers:
        - name: seata-server
          image: acrjcuat01.azurecr.cn/seata-server:1.6.1.jicai
          imagePullPolicy: Always
          env:
            - name: SEATA_PORT
              value: "8091"
            - name: STORE_MODE
              value: db
          ports:
            - name: console
              containerPort: 7091
              protocol: TCP
            - name: service
              containerPort: 8091
              protocol: TCP
          volumeMounts:
          - mountPath: /opt/seata/logs
            name: azurefile
            subPath: seata/logs
          - name: seata-config
            mountPath: /opt/seata/conf
      volumes:
        - name: azurefile
          persistentVolumeClaim:
            claimName: phjc-uat-pvc-azurefile
        - name: seata-config
          configMap:
            name: seata-server-config

```
