### ISSUE TITLE
k8s部署seata，log中的时间慢8小时

### ISSUE THREAD

**Issue by S540J521** [seata/seata#5409]
### Ⅰ. Issue Description
k8s部署seata1.6.1，log文件内容时间慢8小时：进入pod输入date时间与当前时间一致，但是请求接口seata-server生成log的时间比当前时间慢8小时

### Ⅱ. Describe what happened
application.yml关于log的目录如下

```
server:
  port: 7091
spring:
  application:
    name: seata-server
logging:
  config: classpath:logback-spring.xml
  file:
    path: /opt/seata/logs
console:
  user:
    username: seata
    password: seata
```

Dockerfile-seata-server内容如下
```
FROM seataio/seata-server:1.6.1

MAINTAINER www.xxx.com

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

COPY resources/* /seata-server/resources/
```

k8s部署脚本如下
```
apiVersion: v1
kind: Service
metadata:
  name: seata-server
  namespace: default
  labels:
    k8s-app: seata-server
spec:
  type: ClusterIP
  ports:
    - port: 8091
      protocol: TCP
      name: service
    - port: 7091
      protocol: TCP
      name: console
  selector:
    k8s-app: seata-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata-server
  namespace: default
  labels:
    k8s-app: seata-server
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: seata-server
  template:
    metadata:
      labels:
        k8s-app: seata-server
    spec:
      containers:
        - name: seata-server
          image: docker.io/seataio/seata-server:1.6.1
          imagePullPolicy: Always
          env:
            - name: SEATA_PORT
              value: "8091"
            - name: STORE_MODE
              value: db
          ports:
            - name: console
              containerPort: 7091
              protocol: TCP
            - name: service
              containerPort: 8091
              protocol: TCP
          volumeMounts:
          - mountPath: /opt/seata/logs
            name: azurefile
            subPath: seata/logs
      volumes:
        - name: azurefile
          persistentVolumeClaim:
            claimName: xx
```
