### ISSUE TITLE
1.5.2版本server端问题反馈

### ISSUE THREAD

**Issue by 412165137lzh** [seata/seata#5493]
1.5.2的server端配置有问题，修改根目录下的conf\logback\file-appender.xml文件后（比如修改file输出位置），重启server端服务，发现配置无法生效，但是这个问题在1.4.2是不存在的，1.4.2版本修改该文件重启后会立即生效，请问这是什么问题，我应该怎么修改才能生效？

**Comment by a364176773** [comment]
改错了吧，把怎么改的文件发出来看下

**Comment by a364176773** [comment]
```
logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/seata
```
改下application.yml里的file path看下
