### ISSUE TITLE
seata1.6.1版本，配置nacos，存储db。无法登陆后台管理系统，application.yml配置了用户名密码无效,打开后台登陆一直是401

### ISSUE THREAD

**Issue by TripsCoder** [seata/seata#5689]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata1.6.1版本，配置nacos，存储db。无法登陆后台管理系统，application.yml配置了用户名密码无效,打开后台登陆一直是401

### Ⅱ. Describe what happened
nacos版本: 2.1.1
mysql版本: 8.0.27

 本人使用docker-compose部署
仅设置了监听ip和端口 的环境变量

application.yml 配置了用户名和密码如下:
```yml
console:
  user:
    username: seata
    password: abc1234 //用seata一样无法登陆
```
这里用什么密码均无效
登陆返回401,结果如下:
```json
  {
    "timestamp": "2023-06-29T19:28:44.236+00:00",
    "status": 401,
    "error": "Unauthorized",
    "path": "/api/v1/auth/login"
}
```

```
Just paste your stack trace here!
```
### Ⅴ. Anything else we need to know?
希望能够自定义账户密码,并且能够正常登陆.不管用什么方式.

### Ⅵ. Environment:

```yml
      - TZ=Asia/Shanghai
      - SEATA_PORT=8091
      - SEATA_IP=62.234.129.146
```

**Comment by TripsCoder** [comment]
补充: naco服务里面能正常看到 seata-server,并且docker运行日志也没有报错。

**Comment by slievrly** [comment]
Is there an error log at seata-server?

**Comment by slievrly** [comment]
seata console sample: http://demo.seata.io

**Comment by TripsCoder** [comment]
> Is there an error log at seata-server?

17:20:06.453 ERROR --- [     http-nio-7091-exec-5] i.s.c.s.JwtAuthenticationEntryPoint      : Responding with unauthorized error. Message - Full authentication is required to access this resource

the container log  just show this messgae

**Comment by TripsCoder** [comment]
> seata console sample: http://demo.seata.io



> seata console sample: http://demo.seata.io

I think there may be a problem somewhere, but I don't know where. Because everything else is normal except that I can't log in.so come to ask.
I was able to log in to this background when I didn’t set anything before. It’s the default docker startup, but I have a need to change it. User name password and nacos configuration and db as storage.

**Comment by slievrly** [comment]
If we debug the network in the browser, we can see which resources are reporting status 401? Make sure these resources are included in the yml configuration file security.ignore.urls.

![image](https://github.com/seata/seata/assets/8758457/4379a172-5418-4835-af8b-bf1a92aa5739)

**Comment by TripsCoder** [comment]
![image](https://github.com/seata/seata/assets/49176470/0cce2c43-96ef-43b5-8ab1-7db4bcf74012)
```yml
server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/seata
#  extend:
#    logstash-appender:
#      destination: 127.0.0.1:4560
#    kafka-appender:
#      bootstrap-servers: 127.0.0.1:9092
#      topic: logback_to_logstash

console:
  user:
    username: seata
    password: seata

seata:
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: nacos

    nacos:
      server-addr: xxx #nacos地址(手动发评论修改的)
      namespace: xxx #命名空间
      group: DEFAULT_GROUP #分组(手动发评论修改的)
      data-id: seataServer.properties
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: nacos
    nacos:
      application: seata-server
      server-addr: xxx #nacos地址(手动发评论修改的)
      group: DEFAULT_GROUP #分组
      namespace:  xxx#命名空间(手动发评论修改的)
      # tc集群名称
      cluster: default
  # store:
  #   # support: file 、 db 、 redis
  #   mode: file
  #  server:
  #    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
  security:
    secretKey: demokey(手动发评论修改的)
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/loginroot
```
