### ISSUE TITLE
在一个更新表信息的操作业务下，发生了事务超时的异常,我已经将lock_table.row_key修改为longtext类型

### ISSUE THREAD

**Issue by glide-the** [seata/seata#5777]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
在一个更新表信息的操作业务下，发生了事务超时的异常
sql如下，预计更新10个达不溜
```
update set del=0  from message where biz_id = 1 
```
 
根据类似的错误，我搜索了issues，从https://github.com/seata/seata/issues/1904 ，https://github.com/seata/seata/issues/1154 类似的问题，大致可以推测出是lockkey太长，我已经将lock_table.row_key修改为longtext类型，依然出现这个错误

![image](https://github.com/seata/seata/assets/16206043/cd746e0c-04f6-4476-a431-40c7e0186d99)

### Ⅱ. Describe what happened
这个错误的调用位置如下
```
   @GlobalTransactional(timeoutMills=1000000,rollbackFor = Exception.class)  //重点 第一个开启事务的需要添加seata全局事务注解
    public void revokeNoticeTask(NoticeCreateReqVO createReqVO)
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void revokeNotice(Long bizId) 
```
  If there is an exception, please attach the exception trace:
 

```
seata-server  | 20:01:56.448 ERROR --- [verHandlerThread_1_12_500] i.s.s.s.f.s.FileTransactionStoreManager  : writeSession error, compress branch session size exceeded, compressSize : 16761 maxBranchSessionSize : 16384
seata-server  | ==>
seata-server  | java.lang.RuntimeException: compress branch session size exceeded, compressSize : 16761 maxBranchSessionSize : 16384
seata-server  | 	at io.seata.server.session.BranchSession.encode(BranchSession.java:341)
seata-server  | 	at io.seata.server.storage.file.TransactionWriteStore.encode(TransactionWriteStore.java:89)
seata-server  | 	at io.seata.server.storage.file.store.FileTransactionStoreManager.writeSession(FileTransactionStoreManager.java:177)
seata-server  | 	at io.seata.server.session.AbstractSessionManager.writeSession(AbstractSessionManager.java:161)
seata-server  | 	at io.seata.server.session.AbstractSessionManager.addBranchSession(AbstractSessionManager.java:98)
seata-server  | 	at io.seata.server.session.AbstractSessionManager.onAddBranch(AbstractSessionManager.java:137)
seata-server  | 	at io.seata.server.session.GlobalSession.addBranch(GlobalSession.java:296)
seata-server  | 	at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:85)
seata-server  | 	at io.seata.server.storage.file.session.FileSessionManager.lockAndExecute(FileSessionManager.java:182)
seata-server  | 	at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:365)
seata-server  | 	at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:77)
seata-server  | 	at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:102)
seata-server  | 	at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:277)
seata-server  | 	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184)
seata-server  | 	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179)
seata-server  | 	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:131)
seata-server  | 	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179)
seata-server  | 	at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
seata-server  | 	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:511)
seata-server  | 	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:175)
seata-server  | 	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:117)
seata-server  | 	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:281)
seata-server  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
seata-server  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
seata-server  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
seata-server  | 	at java.lang.Thread.run(Thread.java:748)
seata-server  | <==
seata-server  | 
seata-server  | 20:01:56.450 ERROR --- [verHandlerThread_1_12_500] i.s.c.e.AbstractExceptionHandler         : Catch TransactionException while do RPC, request: xid=192.168.168.65:8091:18437597594845185,branchType=AT,resourceId=jdbc:mysql://cola-mysql:3306/cola-cloud-oracle-to-mysql,lockKey=cola_sys_message:20186,20187
----------------------------------------------------
seata-server  | ==>
seata-server  | io.seata.core.exception.BranchTransactionException: Fail to store branch session
seata-server  | 	at io.seata.server.session.AbstractSessionManager.writeSession(AbstractSessionManager.java:172)
seata-server  | 	at io.seata.server.session.AbstractSessionManager.addBranchSession(AbstractSessionManager.java:98)
seata-server  | 	at io.seata.server.session.AbstractSessionManager.onAddBranch(AbstractSessionManager.java:137)
seata-server  | 	at io.seata.server.session.GlobalSession.addBranch(GlobalSession.java:296)
seata-server  | 	at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:85)
seata-server  | 	at io.seata.server.storage.file.session.FileSessionManager.lockAndExecute(FileSessionManager.java:182)
seata-server  | 	at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:365)
seata-server  | 	at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:77)
seata-server  | 	at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:102)
seata-server  | 	at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:277)
seata-server  | 	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184)
seata-server  | 	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179)
seata-server  | 	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:131)
seata-server  | 	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179)
seata-server  | 	at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
seata-server  | 	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:511)
seata-server  | 	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:175)
seata-server  | 	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:117)
seata-server  | 	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:281)
seata-server  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
seata-server  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
seata-server  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
seata-server  | 	at java.lang.Thread.run(Thread.java:748)
seata-server  | <==
seata-server  | 
seata-server  | 20:02:02.097  INFO --- [ttyServerNIOWorker_1_9_16] i.s.c.r.n.AbstractNettyRemotingServer    : channel:[id: 0x2d0615cf, L:/172.25.0.2:8091 - R:/192.168.168.110:52274] read idle.

```

### Ⅲ. Describe what you expected to happen
是否只有关闭at事务这一种办法
Minimal yet complete reproducer code (or URL to code):

 

### Ⅵ. Environment:

- JDK version 1.8
- Seata client/server version:  1.5.1
- Database version:mysql:8
- OS(e.g. `uname -a`):linux
- Others:
- docker container
[docker-seata.tar.gz](https://github.com/seata/seata/files/12321497/docker-seata.tar.gz)
解压后需要手动往target放入1.5.1的服务包，名称为`seata-server.jar`
- springconfig
```
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  # 一定要是false
  enable-auto-data-source-proxy: false
  service:
    vgroupMapping:
      #key與上面的gitegg_seata_tx_group的值對應
      default_tx_group: seata-server
  config:
    type: nacos
    nacos:
      #在安装seata目录下的conf中的register.conf的config节点中下的nacos节点的namespace。如果没有配置 默认public空间
      namespace: ${NACOS_SEATA_NAMESPACE:8694cf5e-5845-422f-9c77-fc3b8f173416}
      # nacos配置中心地址
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      # 分组
      group: 'SEATA_GROUP'
      # nacos的账号和密码
      userName: 'nacos'
      password: 'nacos'
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
       #在安装seata目录下的conf中的register.conf的register节点中下的nacos节点的namespace。如果没有配置 默认public空间
      namespace: ${NACOS_SEATA_NAMESPACE:8694cf5e-5845-422f-9c77-fc3b8f173416}
      userName: 'nacos'
      password: 'nacos'
  store:
    # support: file 、 db 、 redis
    mode: db
    db:
      datasource: druid
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://registry:3306/seata?rewriteBatchedStatements=true
      user: root
      password: 123456
      min-conn: 5
      max-conn: 100
      global-table: global_table
      branch-table: branch_table
      lock-table: lock_table
      distributed-lock-table: distributed_lock
      query-limit: 100
      max-wait: 5000
```
